# Generated by Django 6.0.6 on 2026-06-19 05:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "icono",
                    models.CharField(
                        blank=True,
                        help_text="Clase CSS del ícono, ej: fa-wrench",
                        max_length=50,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "db_table": "categoria",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="MarcaProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="marcas/")),
            ],
            options={
                "verbose_name": "Marca de Repuesto",
                "verbose_name_plural": "Marcas de Repuestos",
                "db_table": "marca_producto",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="MarcaVehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Marca de Vehículo",
                "verbose_name_plural": "Marcas de Vehículos",
                "db_table": "marca_vehiculo",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "contacto",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Persona de contacto"
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("correo", models.EmailField(blank=True, max_length=254)),
                ("direccion", models.TextField(blank=True)),
                ("ciudad", models.CharField(blank=True, max_length=100)),
                (
                    "nit",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="NIT / RUC"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "db_table": "proveedor",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Carrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carrito",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrito",
                "verbose_name_plural": "Carritos",
                "db_table": "carrito",
            },
        ),
        migrations.CreateModel(
            name="ModeloVehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modelos",
                        to="AppMotopart.marcavehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de Vehículo",
                "verbose_name_plural": "Modelos de Vehículos",
                "db_table": "modelo_vehiculo",
                "ordering": ["marca", "nombre"],
                "unique_together": {("marca", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("confirmado", "Confirmado"),
                            ("preparando", "Preparando"),
                            ("enviado", "Enviado"),
                            ("entregado", "Entregado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=15,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("direccion_envio", models.TextField(blank=True)),
                ("notas", models.TextField(blank=True)),
                ("fecha_pedido", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "db_table": "pedido",
                "ordering": ["-fecha_pedido"],
            },
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("transferencia", "Transferencia bancaria"),
                            ("tarjeta", "Tarjeta débito/crédito"),
                            ("efectivo", "Efectivo"),
                            ("contra_entrega", "Contra entrega"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="pendiente",
                        max_length=15,
                    ),
                ),
                (
                    "comprobante",
                    models.ImageField(blank=True, null=True, upload_to="comprobantes/"),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        help_text="Nro. transacción / recibo",
                        max_length=100,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "pedido",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pago",
                        to="AppMotopart.pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "db_table": "pago",
            },
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[("A", "Administrador"), ("C", "Cliente")],
                        default="C",
                        max_length=1,
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("direccion", models.TextField(blank=True)),
                ("ciudad", models.CharField(blank=True, max_length=100)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="perfiles/"),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil",
                "verbose_name_plural": "Perfiles",
                "db_table": "perfil",
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "sku",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código SKU"
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "stock_minimo",
                    models.PositiveIntegerField(
                        default=5, help_text="Alerta de bajo inventario"
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="productos/"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productos",
                        to="AppMotopart.categoria",
                    ),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productos",
                        to="AppMotopart.marcaproducto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "db_table": "producto",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="DetallePedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_producto", models.CharField(max_length=200)),
                ("sku_producto", models.CharField(blank=True, max_length=50)),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="AppMotopart.pedido",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="AppMotopart.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Pedido",
                "verbose_name_plural": "Detalles de Pedido",
                "db_table": "detalle_pedido",
            },
        ),
        migrations.CreateModel(
            name="Promocion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "descuento",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Porcentaje de descuento, ej: 15 = 15%",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("activo", models.BooleanField(default=True)),
                (
                    "productos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="promociones",
                        to="AppMotopart.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promoción",
                "verbose_name_plural": "Promociones",
                "db_table": "promocion",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Movimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("E", "Entrada"),
                            ("S", "Salida por venta"),
                            ("A", "Ajuste manual"),
                            ("C", "Compra a proveedor"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "cantidad",
                    models.IntegerField(help_text="Positivo=entrada, Negativo=salida"),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        help_text="Nro. factura, pedido, etc.",
                        max_length=100,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="AppMotopart.producto",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="AppMotopart.proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Inventario",
                "verbose_name_plural": "Movimientos de Inventario",
                "db_table": "movimiento",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.PositiveIntegerField(verbose_name="Año")),
                ("motor", models.CharField(blank=True, max_length=50)),
                ("version", models.CharField(blank=True, max_length=100)),
                (
                    "combustible",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gasolina", "Gasolina"),
                            ("diesel", "Diésel"),
                            ("hibrido", "Híbrido"),
                            ("electrico", "Eléctrico"),
                            ("gas", "Gas"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiculos",
                        to="AppMotopart.modelovehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehículo",
                "verbose_name_plural": "Vehículos",
                "db_table": "vehiculo",
                "ordering": ["modelo", "-anio"],
            },
        ),
        migrations.CreateModel(
            name="ItemCarrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                ("fecha_agregado", models.DateTimeField(auto_now_add=True)),
                (
                    "carrito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="AppMotopart.carrito",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppMotopart.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem del Carrito",
                "verbose_name_plural": "Ítems del Carrito",
                "db_table": "item_carrito",
                "unique_together": {("carrito", "producto")},
            },
        ),
        migrations.CreateModel(
            name="Compatibilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notas", models.CharField(blank=True, max_length=200)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatibilidades",
                        to="AppMotopart.producto",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatibilidades",
                        to="AppMotopart.vehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compatibilidad",
                "verbose_name_plural": "Compatibilidades",
                "db_table": "compatibilidad",
                "unique_together": {("producto", "vehiculo")},
            },
        ),
    ]
