# Generated by Django 6.0.6 on 2026-06-19 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppMotopart", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Promocion",
        ),
    ]
