# Generated by Django 6.0.6 on 2026-06-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppMotopart", "0002_delete_promocion"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="documento",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
