# Generated by Django 6.0.6 on 2026-06-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppMotopart", "0003_perfil_documento"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="departamento",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
